import { FlaskConical, Sparkles } from "lucide-react"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip"
import { cn } from "@/lib/utils"

const PROVIDER_LABEL: Record<string, string> = {
  openai: "OpenAI",
  gemini: "Gemini",
  wayinvideo: "WayinVideo",
  demo: "Demo",
}

/** Honest labeling: every AI result says whether it came from a real model or demo logic. */
export function SourceBadge({ source, provider, className }: { source: "ai" | "demo"; provider?: string; className?: string }) {
  const isDemo = source === "demo"
  return (
    <Tooltip>
      <TooltipTrigger
        render={
          <span
            tabIndex={0}
            className={cn(
              "inline-flex h-6 items-center gap-1 rounded-full border px-2 text-[11px] font-medium outline-none focus-visible:ring-3 focus-visible:ring-ring/50",
              isDemo
                ? "border-warning/30 bg-warning/10 text-amber-700 dark:text-amber-300"
                : "border-success/30 bg-success/10 text-green-700 dark:text-green-300",
              className
            )}
          />
        }
      >
        {isDemo ? <FlaskConical className="size-3" /> : <Sparkles className="size-3" />}
        {isDemo ? "Demo data" : `Real AI · ${PROVIDER_LABEL[provider ?? ""] ?? provider}`}
      </TooltipTrigger>
      <TooltipContent className="max-w-64">
        {isDemo
          ? "Generated by Kontenin's built-in rule-based demo engine — not a language model. Add an API key to enable real AI."
          : `Generated by ${PROVIDER_LABEL[provider ?? ""] ?? "an AI provider"} on the server.`}
      </TooltipContent>
    </Tooltip>
  )
}
